"""Presentation labels for scientific engine parameters; script keys stay unchanged."""

TEMPLATE_FIELDS = {'seed': 'Semente aleatória',
 'scoring': 'Função de pontuação',
 'write_fragment_libraries': 'Escrever bibliotecas de fragmentos',
 'user_specified_anchor': 'Âncora definida pelo usuário',
 'limit_max_anchors': 'Limitar quantidade de âncoras',
 'min_anchor_size': 'Tamanho mínimo da âncora',
 'pruning_use_clustering': 'Agrupar conformações durante a poda',
 'pruning_max_orients': 'Máximo de orientações na poda',
 'pruning_clustering_cutoff': 'Limiar de agrupamento na poda',
 'pruning_conformer_score_cutoff': 'Limiar de score de conformações na poda',
 'pruning_conformer_score_scaling_factor': 'Fator de escala do score de conformações na poda',
 'pruning_orient_score_cutoff': 'Limiar de score de orientações na poda',
 'use_clash_overlap': 'Considerar sobreposição de colisões',
 'write_growth_tree': 'Escrever árvore de crescimento',
 'use_internal_energy': 'Considerar energia interna',
 'internal_energy_rep_exp': 'Expoente repulsivo da energia interna',
 'internal_energy_cutoff': 'Limiar de energia interna',
 'limit_max_ligands': 'Limitar quantidade de ligantes',
 'skip_molecule': 'Ignorar molécula',
 'read_mol_solvation': 'Ler solvatação molecular',
 'calculate_rmsd': 'Calcular RMSD',
 'use_rmsd_reference_mol': 'Usar molécula de referência para RMSD',
 'use_database_filter': 'Usar filtro de banco de dados',
 'orient_ligand': 'Orientar ligante',
 'automated_matching': 'Correspondência automática',
 'max_orientations': 'Máximo de orientações',
 'critical_points': 'Pontos críticos',
 'chemical_matching': 'Correspondência química',
 'use_ligand_spheres': 'Usar esferas do ligante',
 'bump_filter': 'Filtro de colisões',
 'score_molecules': 'Pontuar moléculas',
 'contact_score_primary': 'Score primário de contato',
 'grid_score_primary': 'Score primário da grade',
 'grid_score_rep_rad_scale': 'Escala do raio repulsivo da grade',
 'grid_score_vdw_scale': 'Escala de van der Waals da grade',
 'grid_score_es_scale': 'Escala eletrostática da grade',
 'grid_lig_efficiency': 'Eficiência do ligante na grade',
 'minimize_ligand': 'Minimizar ligante',
 'minimize_anchor': 'Minimizar âncora',
 'minimize_flexible_growth': 'Minimizar crescimento flexível',
 'minimize_flexible_growth_ramp': 'Rampa de minimização do crescimento flexível',
 'use_advanced_simplex_parameters': 'Usar parâmetros avançados do simplex',
 'simplex_max_cycles': 'Máximo de ciclos do simplex',
 'simplex_score_converge': 'Convergência de score do simplex',
 'simplex_cycle_converge': 'Convergência de ciclos do simplex',
 'simplex_trans_step': 'Passo de translação do simplex',
 'simplex_rot_step': 'Passo de rotação do simplex',
 'simplex_tors_step': 'Passo de torção do simplex',
 'simplex_anchor_max_iterations': 'Máximo de iterações da âncora no simplex',
 'simplex_grow_max_iterations': 'Máximo de iterações de crescimento no simplex',
 'simplex_grow_tors_premin_iterations': 'Iterações de pré-minimização torsional de crescimento no '
                                        'simplex',
 'simplex_random_seed': 'Semente aleatória do simplex',
 'simplex_restraint_min': 'Minimização com restrições do simplex',
 'simplex_final_min': 'Minimização final do simplex',
 'atom_model': 'Modelo atômico',
 'write_orientations': 'Escrever orientações',
 'write_mol_solvation': 'Escrever solvatação molecular',
 'num_scored_conformers': 'Número de conformações pontuadas',
 'rank_ligands': 'Ordenar ligantes por score',
 'score_threshold': 'Limiar de score',
 'conformer_search_type': 'Tipo de busca de conformações',
 'multigrid_score_primary': 'Score primário de múltiplas grades',
 'dock3.5_score_primary': 'Score primário DOCK3.5',
 'continuous_score_primary': 'Score primário contínuo',
 'footprint_similarity_score_primary': 'Score primário de similaridade de footprint',
 'fps_score_use_footprint_reference_mol2': 'Usar MOL2 de referência para footprint',
 'fps_score_foot_compare_type': 'Tipo de comparação de footprint',
 'fps_score_normalize_foot': 'Normalizar footprint',
 'fps_score_foot_comp_all_residue': 'Comparar footprint de todos os resíduos',
 'fps_score_vdw_att_exp': 'Expoente atrativo de van der Waals do footprint',
 'fps_score_vdw_rep_exp': 'Expoente repulsivo de van der Waals do footprint',
 'fps_score_vdw_rep_rad_scale': 'Escala do raio repulsivo de van der Waals do footprint',
 'fps_score_use_distance_dependent_dielectric': 'Usar dielétrico dependente da distância no '
                                                'footprint',
 'fps_score_dielectric': 'Dielétrico do footprint',
 'fps_score_vdw_fp_scale': 'Escala de van der Waals do footprint',
 'fps_score_es_fp_scale': 'Escala eletrostática do footprint',
 'fps_score_hb_fp_scale': 'Escala de ligações de hidrogênio do footprint',
 'write_footprints': 'Escrever footprints',
 'write_hbonds': 'Escrever ligações de hidrogênio',
 'allow_non_integral_charges': 'Permitir cargas não inteiras',
 'compute_grids': 'Calcular grades',
 'grid_spacing': 'Espaçamento da grade',
 'output_molecule': 'Gerar molécula de saída',
 'contact_score': 'Score de contato',
 'energy_score': 'Score de energia',
 'energy_cutoff_distance': 'Distância limite para energia',
 'attractive_exponent': 'Expoente atrativo',
 'repulsive_exponent': 'Expoente repulsivo',
 'distance_dielectric': 'Dielétrico dependente da distância',
 'dielectric_factor': 'Fator dielétrico',
 'bump_overlap': 'Sobreposição de colisões',
 'contact_score_secondary': 'Score secundário de contato',
 'grid_score_secondary': 'Score secundário da grade',
 'multigrid_score_secondary': 'Score secundário de múltiplas grades',
 'dock3.5_score_secondary': 'Score secundário DOCK3.5',
 'continuous_score_secondary': 'Score secundário contínuo',
 'footprint_similarity_score_secondary': 'Score secundário de similaridade de footprint',
 'pharmacophore_score_secondary': 'Score secundário de farmacóforo',
 'descriptor_score_secondary': 'Score secundário de descritor',
 'gbsa_zou_score_secondary': 'Score secundário GBSA Zou',
 'gbsa_hawkins_score_secondary': 'Score secundário GBSA Hawkins',
 'SASA_score_secondary': 'Score secundário SASA',
 'amber_score_secondary': 'Score secundário AMBER',
 'simplex_max_iterations': 'Máximo de iterações do simplex',
 'simplex_tors_premin_iterations': 'Iterações de pré-minimização torsional do simplex',
 'simplex_coefficient_restraint': 'Coeficiente de restrição do simplex'}
